INSERT INTO DeAnCongTy.THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('001', 'Minh', 'Nam', '1932-02-29', 'Vợ chồng ');
INSERT INTO DeAnCongTy.THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('005', 'Khang', 'Nam', '1973-10-25', 'Con trai ');
INSERT INTO DeAnCongTy.THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('005', 'Phương', 'Nữ', '1948-05-03', 'Vợ chồng ');
INSERT INTO DeAnCongTy.THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('005', 'Trinh', 'Nữ', '1976-04-05', 'Con gái ');
INSERT INTO DeAnCongTy.THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('009', 'Châu', 'Nữ', '1978-12-30', 'Con gái ');
INSERT INTO DeAnCongTy.THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('009', 'Phương', 'Nữ', '1957-05-05', 'Vợ chồng ');
INSERT INTO DeAnCongTy.THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES ('009', 'Tiến', 'Nam', '1978-01-01', 'Con trai ');