INSERT INTO DeAnCongTy.DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES ('San pham X ', 1, 'Vũng Tàu ', 5);
INSERT INTO DeAnCongTy.DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES ('San pham Y ', 2, 'Nha Trang ', 5);
INSERT INTO DeAnCongTy.DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES ('San pham Z ', 3, 'TP HCM', 5);
INSERT INTO DeAnCongTy.DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES ('Tin hoc hoa', 10, 'Hà Nội', 4);
INSERT INTO DeAnCongTy.DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES ('Cap quang', 20, 'TP HCM', 1);
INSERT INTO DeAnCongTy.DEAN (TENDA, MADA, DDIEM_DA, PHONG) VALUES ('Dao tao', 30, 'Hà Nội', 4);