INSERT INTO DeAnCongTy.PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC) VALUES ('Quản lý ', 1, '6', '1971-06-19');
INSERT INTO DeAnCongTy.PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC) VALUES ('Điều hành ', 4, '8', '1985-01-01');
INSERT INTO DeAnCongTy.PHONGBAN (TENPHG, MAPHG, TRPHG, NG_NHANCHUC) VALUES ('Nghiên cứu ', 5, '5', '1978-05-22');