INSERT INTO DeAnCongTy.DIADIEM_PHG (MAPHG, DIADIEM) VALUES (1, 'TP HCM');
INSERT INTO DeAnCongTy.DIADIEM_PHG (MAPHG, DIADIEM) VALUES (4, 'Hà Nội');
INSERT INTO DeAnCongTy.DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, 'NHA TRANG');
INSERT INTO DeAnCongTy.DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, 'TAU');
INSERT INTO DeAnCongTy.DIADIEM_PHG (MAPHG, DIADIEM) VALUES (5, 'TP HCM');