INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (1, 1, 'Thiet ke san pham X ');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (1, 2, 'Thu nghiem san pham X ');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (2, 1, 'San xuat san pham Y ');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (2, 2, 'Quang cao san pham Y ');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (3, 1, 'Khuyen mai san pham Z');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (10, 1, 'Tin hoc hoa nhan su tien luong');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (10, 2, 'Tin hoc hoa phong Kinh doanh');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (20, 1, 'Lap dat cap quang');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (30, 1, 'Dao tao nhan vien Marketing');
INSERT INTO DeAnCongTy.CONGVIEC (MADA, STT, TEN_CONG_VIEC) VALUES (30, 2, 'Dao tao chuyen vien vien thiet ke');